//! Error types for the FIUDP sender.
//!
//! This module defines [`FiudpError`], the single typed error enum that
//! covers every fallible operation in the crate, and a convenience
//! [`Result`] alias that defaults the error type.
//!
//! Consumers can `match` on specific variants to handle failures
//! programmatically rather than relying on opaque error strings.

use std::io;

/// Typed error enum for all fallible operations in the FIUDP sender.
///
/// Unlike opaque error types, `FiudpError` lets downstream consumers
/// `match` on specific failure modes and handle them programmatically.
///
/// # Example
///
/// ```rust,no_run
/// use fiudp_cli::{Args, Config, run, FiudpError};
/// use clap::Parser;
///
/// let args = Args::parse();
/// let config = Config::try_from(args).unwrap();
/// match run(config) {
///     Ok(()) => println!("sent"),
///     Err(FiudpError::EmptyInput) => eprintln!("nothing to send"),
///     Err(e) => eprintln!("error: {e}"),
/// }
/// ```
#[derive(Debug, thiserror::Error)]
pub enum FiudpError {
    /// The `--parity-ratio` value exceeds the valid range of 0–100.
    ///
    /// The parity ratio controls the percentage of redundancy shards
    /// generated by the Reed-Solomon encoder. Values above 100% are
    /// nonsensical and rejected at configuration time.
    #[error("invalid parity ratio {0}: must be 0–100")]
    InvalidParityRatio(u8),

    /// The key file does not contain exactly 32 bytes.
    ///
    /// ChaCha20-Poly1305 requires a 256-bit (32-byte) pre-shared key.
    /// This error is raised when the key file exists but has the wrong
    /// length, which likely indicates a truncated or corrupt file.
    #[error("key file must contain exactly 32 bytes, got {0}")]
    InvalidKeyLength(usize),

    /// The session ID file exists but does not contain exactly 2 bytes.
    ///
    /// The session ID is stored as a big-endian `u16` alongside the key
    /// file (with a `.session_id` extension). If the file is present but
    /// malformed, this error is raised rather than silently resetting.
    #[error("session_id file must contain exactly 2 bytes")]
    InvalidSessionFile,

    /// The monotonic session counter reached `u16::MAX` (65 535).
    ///
    /// Because the AEAD nonce is derived from the session ID, reusing a
    /// session ID under the same key would break nonce uniqueness.
    /// Rotate the PSK and reset the receiver state before continuing.
    #[error("session_id overflow (u16::MAX reached); rotate PSK and reset receiver state")]
    SessionIdOverflow,

    /// The input frame is empty (zero bytes after reading).
    ///
    /// Sending an empty frame is meaningless and would produce zero data
    /// shards, which is invalid for Reed-Solomon encoding.
    #[error("input is empty")]
    EmptyInput,

    /// The total number of shards (data + parity) exceeds `u16::MAX`.
    ///
    /// Shard indices are encoded as `u16` in the wire format (see §3.4
    /// of SPEC.md), so exceeding 65 535 total shards is not representable.
    #[error("total shards {0} exceeds u16 limit")]
    TooManyShards(usize),

    /// A shard payload has an unexpected size (internal invariant violation).
    ///
    /// Every shard — data or parity — must be exactly [`SHARD_SIZE`](crate::SHARD_SIZE)
    /// bytes. This error indicates a bug in the padding or slicing logic.
    #[error("invalid shard size {actual}, expected {expected}")]
    InvalidShardSize {
        /// Actual size received.
        actual: usize,
        /// Expected [`SHARD_SIZE`](crate::SHARD_SIZE).
        expected: usize,
    },

    /// A UDP send wrote fewer bytes than the full packet.
    ///
    /// On most platforms, UDP sends are atomic, but the POSIX API allows
    /// short writes. This error captures the discrepancy for diagnostics.
    #[error("short UDP send: {sent} of {expected} bytes")]
    ShortSend {
        /// Bytes actually sent by the OS.
        sent: usize,
        /// Bytes expected to send ([`PACKET_SIZE`](crate::PACKET_SIZE)).
        expected: usize,
    },

    /// ChaCha20-Poly1305 encryption failed.
    ///
    /// In practice this should never happen with valid inputs, but the
    /// AEAD API is fallible and the error is propagated for completeness.
    #[error("encryption failed: {0}")]
    Encryption(String),

    /// Reed-Solomon FEC encoding failed.
    ///
    /// This can occur if the encoder is given invalid shard counts (e.g.
    /// zero data shards), which is guarded against upstream.
    #[error("FEC encoding failed: {0}")]
    Fec(String),

    /// An I/O operation failed, with context describing which operation.
    ///
    /// The `context` field provides a human-readable description of what
    /// was being attempted (e.g. "failed to read key file ./psk.bin"),
    /// while `source` carries the underlying OS error.
    #[error("{context}")]
    Io {
        /// Human-readable description of the failed operation.
        context: String,
        /// The underlying I/O error.
        #[source]
        source: io::Error,
    },
}

/// Convenience alias used throughout the crate.
///
/// Equivalent to `std::result::Result<T, FiudpError>`.
pub type Result<T> = std::result::Result<T, FiudpError>;
